const messages = {
  uz: {
    language: "UZ",
    service: "XIZMATLARIMIZ",
    experience: "TAJRIBA",
    testimonials: "MIJOZLAR FIKRI",
    there: "Hey Salom,",
    i: "Men",
    quote1: "Men chiroyli narsalarni dizayn qilaman",
    quote2: "va qilayotgan ishimni yaxshi ko'raman",
    certify1: "SERTIFIKATLANGAN TAJRIBALI",
    certify2: "GRAFIK DIZAYNER",
    year: "Yil",
    graphic: "Grafik dizayn",
    opinion: "Mijozlar fikri men haqimda",
    opinion2: "O'z soxasining ustalari va o'z biznesini rivojlantirish uchun",
    opinion3: "men bilan shartnoma qilgan mijozlar",
  },
  en: {
    language: "EN",
    service: "SERVICES",
    experience: "EXPERIENCE",
    testimonials: "TESTIMONIALS",
    there: "Hey There,",
    i: "I'm",
    quote1: "I design beautiful simple",
    quote2: "things, And I love what i do",
    certify1: "CERTIFIED PROFESSIONAL",
    certify2: "GRAPHIC DESIGNER",
    year: "Years",
    graphic: "Graphic Design",
    opinion: "Clients feedback about me",
    opinion2: "Masters of their field and to develop their own business",
    opinion3: "clients who have signed a contract with me",
  },
};

export default messages;
